### ISSUE TITLE
There is no implement of permute_dimensions() function in BilinearUpSampling.py

### ISSUE THREAD

**Issue by tqwhdx19** [MrGiovanni/ModelsGenesis#1]
I don't find the implement of permute_dimensions() function in BilinearUpSampling.py

**Comment by MrGiovanni** [comment]
Thanks for pointing it out. 
The function permute_dimensions() is defined in keras.backend
see [https://keras.io/backend/](https://keras.io/backend/)
So you may want to use it as 
```
import keras.backend as K
X = K.permute_dimensions(X, [0, 3, 1, 2])
```
As BilinearUpSampling.py was actually not used in my implementation, so I did not notice this bug.

I have now commented out the line
`from utils.BilinearUpSampling import *`
in Genesis_Chest_CT.py and also updated BilinearUpSampling.py

Thank you very much!
