### ISSUE TITLE
Pretrained weight for pytorch

### ISSUE THREAD

**Issue by zhanghaoyue** [MrGiovanni/ModelsGenesis#15]
It seems that the pretrained weight .h5 is for Keras. Could you please provide .pth pretrained weight for Pytorch?

Thank you

**Comment by MrGiovanni** [comment]
Hi @zhanghaoyue 

We have provided the implementation of Models Genesis in PyTorch — the pre-trained .pt weights will be released soon. We are currently verifying its performance on multiple target tasks (basically redo all the experiments in PyTorch version) to ensure the released .pt weights offering transferability as good as the pre-trained .h5 weights.

Hopefully, the pre-trained .pt weights would be released before mid-Feb.

Best,
Zongwei

**Comment by zhanghaoyue** [comment]
Thank you! glad to know!
