### ISSUE TITLE
Code for 2D self-supervision transformations

### ISSUE THREAD

**Issue by AntanasKascenas** [MrGiovanni/ModelsGenesis#16]
Hi,

Thank you for releasing your code, I very much appreciate the extensive experiments in your paper.

I'd like to compare your self-supervision training procedure against a different self-supervision task on some different 2D medical imaging data. Would you be able to release the code you used to transform your 2D data when making comparisons against ImageNet (just the transformation code would be enough for me, not necessarily the whole 2D training procedure)? I imagine the code is pretty similar to your 3D code, but it would be nice to get the right parameters from you. 

Since training on 3D is rather resource intensive, do you think that 2D pretraining performance is a good indicator to compare among different self-supervision tasks?

**Comment by MrGiovanni** [comment]
Hi,

Thank you for your interest! Honestly, I am also wondering how our Models Genesis 2D comparing with other self-supervised learning approaches under the same 2D experimental setup. It's exciting to hear that you are planning to do so. 

I would be very happy to provide you our code and even pre-trained 2D models. Please do not hesitate to contact me via email.

Best,
Zongwei
