### ISSUE TITLE
Help with Cube Generator

### ISSUE THREAD

**Issue by mistermoutan** [MrGiovanni/ModelsGenesis#20]
Hello! When looking at your Readme.MD you mention that the infinite_cube_generator.py generates N cubes from each patient, N is the scale correct?

However, when using your own 3D extraced cubes from luna, when opening the file from a single patient, there are a lot more than 32 cubes. For example bat_32_s_64x64x32_0.npy has dimensions of  (2848, 64, 64, 32) which are 2848 cubes. Could you explain to me what scale represents then in your code and what you use scale for when generating cubes? Did you extract the cubes you provided with a much larger scale?

Also, could you please explain the difference between the purpose of input_rows and crop_rows?

**Comment by MrGiovanni** [comment]
Hi @mistermoutan 

32 means I extracted 32 sub-volumes per patient, 64 means 64 sub-volumes per patient. There are many patients within each fold in the LUNA16 dataset, so the npy file includes all the sub-volume extracted from one fold.

Thanks,
Zongwei

**Comment by mistermoutan** [comment]
Thank you!
