### ISSUE TITLE
How much data when pretraining ?

### ISSUE THREAD

**Issue by mini-Shark** [MrGiovanni/ModelsGenesis#21]
Hi Zongwei,

Thanks for your great work. Your implemention is very clearly 👍 
I'm trying to pretrain on mine own dataset, but i don't know how much training data been used when you pretrain (patch level). Could you tell me this detail ?

Thanks,
Jing

**Comment by MrGiovanni** [comment]
Hi @mini-Shark 

The sub-volumes used in our work are publicly available. You can find the details here:
https://github.com/MrGiovanni/ModelsGenesis/tree/master/pytorch#for-your-convenience-we-have-provided-our-own-extracted-3d-cubes-from-luna16

Please let me know if you have further questions.

Thank you,
Zongwei

**Comment by mini-Shark** [comment]
Thanks for your @MrGiovanni  quick reply. I'm very appreciate.
