### ISSUE TITLE
pre-training weight

### ISSUE THREAD

**Issue by tan416tan** [MrGiovanni/ModelsGenesis#22]
Hello, I have two questions.
1.I would like to ask if I want to use your pre-training weight, do I have to use your model as my feature extraction model?
2.Can you provide a link to download your pre-training weights?

**Comment by MrGiovanni** [comment]
Hi @tan416tan 

1. You could use my pre-trained weights as feature extractor, fine-tune my pre-trained weights, or pre-train on your own dataset/architecture using my code. It all depends on what you need.

2. Our pre-trained weights are publicly available, supporting keras and pytorch:

- Download keras weights: https://github.com/MrGiovanni/ModelsGenesis/tree/master/keras#2-download-the-pre-trained-models-genesis
- Download pytorch weights: https://github.com/MrGiovanni/ModelsGenesis/tree/master/pytorch#2-download-the-pre-trained-models-genesis

Thank you,
Zongwei

**Comment by tan416tan** [comment]
> Hi @tan416tan
> 
> 1. You could use my pre-trained weights as feature extractor, fine-tune my pre-trained weights, or pre-train on your own dataset/architecture using my code. It all depends on what you need.
> 2. Our pre-trained weights are publicly available, supporting keras and pytorch:
> 
> * Download keras weights: https://github.com/MrGiovanni/ModelsGenesis/tree/master/keras#2-download-the-pre-trained-models-genesis
> * Download pytorch weights: https://github.com/MrGiovanni/ModelsGenesis/tree/master/pytorch#2-download-the-pre-trained-models-genesis
> 
> Thank you,
> Zongwei

Ok,Thank you very much！
