### ISSUE TITLE
Transformations too slow for training

### ISSUE THREAD

**Issue by elsaschalck** [MrGiovanni/ModelsGenesis#24]
Hello, 
I’m using some image transformations of Models Genesis (local pixel shuffling, non-linear transformation, in- and out-painting) to train an autoencodeur. As I’m working with 2D images, I adapted the code available to process 2D images. The transformations appear to work successfully. 
However, they’re really time-consuming : on average 20 seconds per batch, with a batch size of 128 2D images. Because of this, training is impossible as it is far too slow. I tried decreasing the probability of each transformation (from 0.5 to 0.25), decreasing the number of blocks in pixel shuffling and using less transformations, which helped, but the process remains too slow. 
Did you face the same issue during training? If yes, how did you overcome this issue? 
Thank you !

**Comment by MrGiovanni** [comment]
Hi @elsaschalck 

Thanks for reaching out.

> they’re really time-consuming

The released code is mainly for research purposes so it has not been _fully_ optimized in terms of speed. I would suggest you use **multiple workers (CPU)** or optimize the implementation of image transformations upon your needs.

> I tried decreasing the probability of each transformation (from 0.5 to 0.25), decreasing the number of blocks in pixel shuffling and using less transformations

It can surely speed up training but may not help model learn strong representation :-)

Hope it is helpful.

Zongwei

**Comment by elsaschalck** [comment]
Hi @MrGiovanni 
Thanks you for answer and for your help. 
I'll try to use multiple workers to speed up the process, as recommended :-) !

Elsa
