### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by evanmy** [MrGiovanni/ModelsGenesis#32]
Hi,

I find your work very interesting. I have tried to open a request for the pretrained weights, but it seems the [link](https://www.wjx.top/jq/46747127.aspx) is down.

**Comment by MrGiovanni** [comment]
The link works for me, but I can give you the download link as below:

> You can download our weights here:
> 
> https://drive.google.com/drive/folders/1H_e0PKPJSRwnAulE3XAQqfcgtK1gK8Cq?usp=sharing
> 
> Alternatively, for the one who cannot access Google, please download here
> Link: https://pan.baidu.com/s/1Qnb1M9i0eeMZ_C416wm1bw Pass: 72c7

Thank you,
Zongwei

**Comment by evanmy** [comment]
Thank you!
