### ISSUE TITLE
about the input size

### ISSUE THREAD

**Issue by shiontao** [MrGiovanni/ModelsGenesis#4]
I am recreating your article, can the network input be changed to 128*128*128 without changing other parameters?

**Comment by MrGiovanni** [comment]
Yes, 128x128x128 works if it fits your GPUs. Any size that could be divided evenly by 16 (=2^4) is okay because of 4 down-sampling layers in V-Net. Our recommendation is 64x64x32.

Thanks for your question.

Zongwei
