### ISSUE TITLE
Pretrained model for Model Genesis Chest CT 2D

### ISSUE THREAD

**Issue by HiokHian** [MrGiovanni/ModelsGenesis#41]
Thank you for all the hard work put into this project and for making the pretrained models and code available for public use! Would it be possible to also provide the code and pretrained weights for the 2D models, in particular Genesis Chest CT 2D, as mentioned in the paper?

**Comment by Jingnan-Jia** [comment]
Looking forward to Genesis Chest CT/X-ray 2D, as well.

**Comment by dongdongtong** [comment]
+1

**Comment by danielqingz** [comment]
+1 Thank you!

**Comment by MrGiovanni** [comment]
Hi,

Our pre-trained 2D Models Genesis can be found here:
https://drive.google.com/drive/folders/1SHKFPCaIwYXmKQbDPECnq3cKFEf8yrq9?usp=sharing

Note that the 2D backbone of our encoder is ResNet18.

Best regards,

Zongwei

**Comment by MrGiovanni** [comment]
Hi,

The previous link was expired. Here is the new link:

https://livejohnshopkins-my.sharepoint.com/:f:/g/personal/zzhou82_jh_edu/Eu3b9ujiMZBNm48e_HdbcE0BjzGd0P2IyW9HjOAAjQry9Q?e=8CU68j

Best regards,

Zongwei
