### ISSUE TITLE
Problems about the parameter len_depth

### ISSUE THREAD

**Issue by zjjJacinthe** [MrGiovanni/ModelsGenesis#50]
Hello! So interested in your work.@MrGiovanni 
I don't quite understand what the parameter “len_depth” is for in infinite_generator_3D.py.
Could you please tell me more about that?

        for d in range(config.input_deps):
            for i in range(config.input_rows):
                for j in range(config.input_cols):
                    for k in range(config.len_depth):
                        if crop_window[i, j, d+k] >= config.HU_thred:
                            t_img[i, j, d] = crop_window[i, j, d+k]
                            d_img[i, j, d] = k
                            break
                        if k == config.len_depth-1:
                            d_img[i, j, d] = k
                            
        d_img = d_img.astype('float32')
        d_img /= (config.len_depth - 1)
        d_img = 1.0 - d_img

**Comment by Beenking** [comment]
so, what's meaning of “len_depth”
