### ISSUE TITLE
Question about LUNA16 FPR test set

### ISSUE THREAD

**Issue by torki-hossein** [MrGiovanni/ModelsGenesis#53]
Thanks for your excellent paper and repo, 
As you mentioned in the infinite_generator_3D code, you used folds 7,8,9 as test data, did you compute your reported cpm (0.971 in the paper) just on these folds?
thanks a lot.

**Comment by MrGiovanni** [comment]
Hi @torki-hossein 

Correct, the folds 7-9 were used for testing in the target task (NCC).

Best,

Zongwei

**Comment by torki-hossein** [comment]
> Hi @torki-hossein
> 
> Correct, the folds 7-9 were used for testing in the target task (NCC).
> 
> Best,
> 
> Zongwei

Thanks.
